window.ACTIVITY_DATA = [
  {
    "ts": "2026-03-23T14:32:00Z",
    "session": "a1b2c3d4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "fix the login redirect loop that happens when the session cookie expires mid-request. users are getting stuck in an infinite redirect between /login and /dashboard",
    "response": "Fixed the issue by updating the error handling logic.",
    "effort_total": 19,
    "duration_s": 356,
    "slug": "eager-dancing-fox",
    "branch": "fix/auth-redirect",
    "session_file": null
  },
  {
    "ts": "2026-03-23T14:28:00Z",
    "session": "a1b2c3d4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "add rate limiting middleware to the /api/auth endpoints. we're seeing brute force attempts in the logs",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 13,
    "duration_s": 234,
    "slug": "eager-dancing-fox",
    "branch": "fix/auth-redirect",
    "session_file": null
  },
  {
    "ts": "2026-03-23T14:15:00Z",
    "session": "a1b2c3d4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "review the auth middleware chain and check if there are any gaps in the CSRF protection",
    "response": "Reviewed the implementation and identified key areas for improvement.",
    "effort_total": 11,
    "duration_s": 204,
    "slug": "eager-dancing-fox",
    "branch": "fix/auth-redirect",
    "session_file": null
  },
  {
    "ts": "2026-03-23T14:01:00Z",
    "session": "a1b2c3d4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "research best practices for JWT refresh token rotation in express.js applications",
    "response": "Reviewed the implementation and identified key areas for improvement.",
    "effort_total": 11,
    "duration_s": 192,
    "slug": "eager-dancing-fox",
    "branch": "fix/auth-redirect",
    "session_file": null
  },
  {
    "ts": "2026-03-23T13:45:00Z",
    "session": "e5f6g7h8",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "run the e2e test suite and fix any failures related to the new auth flow",
    "response": "Tests passed successfully. All assertions verified.",
    "effort_total": 10,
    "duration_s": 174,
    "slug": "calm-testing-bear",
    "branch": "test/auth-e2e",
    "session_file": null
  },
  {
    "ts": "2026-03-23T13:38:00Z",
    "session": "e5f6g7h8",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "update the playwright config to add retry logic for flaky auth tests",
    "response": "Refactored the code to use the new pattern while maintaining backward compatibility.",
    "effort_total": 9,
    "duration_s": 166,
    "slug": "calm-testing-bear",
    "branch": "test/auth-e2e",
    "session_file": null
  },
  {
    "ts": "2026-03-23T13:22:00Z",
    "session": "e5f6g7h8",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "test the password reset flow end-to-end including the email verification step",
    "response": "Tests passed successfully. All assertions verified.",
    "effort_total": 10,
    "duration_s": 184,
    "slug": "calm-testing-bear",
    "branch": "test/auth-e2e",
    "session_file": null
  },
  {
    "ts": "2026-03-23T13:10:00Z",
    "session": "i9j0k1l2",
    "project": "infra",
    "cwd": "/home/dev/repos/infra",
    "prompt": "deploy the staging environment with the new redis cluster config",
    "response": "Tests passed successfully. All assertions verified.",
    "effort_total": 9,
    "duration_s": 158,
    "slug": "swift-deploying-eagle",
    "branch": "infra/redis-migration",
    "session_file": null
  },
  {
    "ts": "2026-03-23T12:55:00Z",
    "session": "i9j0k1l2",
    "project": "infra",
    "cwd": "/home/dev/repos/infra",
    "prompt": "check the terraform plan output for the redis migration. make sure we're not destroying the existing cluster",
    "response": "Reviewed the implementation and identified key areas for improvement.",
    "effort_total": 13,
    "duration_s": 246,
    "slug": "swift-deploying-eagle",
    "branch": "infra/redis-migration",
    "session_file": null
  },
  {
    "ts": "2026-03-23T12:40:00Z",
    "session": "i9j0k1l2",
    "project": "infra",
    "cwd": "/home/dev/repos/infra",
    "prompt": "add monitoring alerts for redis memory usage and connection pool exhaustion",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 10,
    "duration_s": 180,
    "slug": "swift-deploying-eagle",
    "branch": "infra/redis-migration",
    "session_file": null
  },
  {
    "ts": "2026-03-23T12:20:00Z",
    "session": "m3n4o5p6",
    "project": "docs",
    "cwd": "/home/dev/repos/docs",
    "prompt": "write the API migration guide for v2 endpoints. include examples for each breaking change",
    "response": "Documentation updated with comprehensive examples and migration notes.",
    "effort_total": 11,
    "duration_s": 208,
    "slug": "gentle-writing-owl",
    "branch": "docs/api-v2-guide",
    "session_file": null
  },
  {
    "ts": "2026-03-23T12:05:00Z",
    "session": "m3n4o5p6",
    "project": "docs",
    "cwd": "/home/dev/repos/docs",
    "prompt": "update the authentication section to cover the new OAuth2 PKCE flow we just shipped",
    "response": "Refactored the code to use the new pattern while maintaining backward compatibility.",
    "effort_total": 11,
    "duration_s": 196,
    "slug": "gentle-writing-owl",
    "branch": "docs/api-v2-guide",
    "session_file": null
  },
  {
    "ts": "2026-03-23T11:48:00Z",
    "session": "a1b2c3d4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "refactor the session store from in-memory to redis-backed. keep the interface compatible",
    "response": "Refactored the code to use the new pattern while maintaining backward compatibility.",
    "effort_total": 11,
    "duration_s": 206,
    "slug": "eager-dancing-fox",
    "branch": "fix/auth-redirect",
    "session_file": null
  },
  {
    "ts": "2026-03-23T11:30:00Z",
    "session": "a1b2c3d4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "explain how the current middleware chain handles token refresh and where the race condition occurs",
    "response": "Reviewed the implementation and identified key areas for improvement.",
    "effort_total": 12,
    "duration_s": 226,
    "slug": "eager-dancing-fox",
    "branch": "fix/auth-redirect",
    "session_file": null
  },
  {
    "ts": "2026-03-23T11:15:00Z",
    "session": "q7r8s9t0",
    "project": "mobile-app",
    "cwd": "/home/dev/repos/mobile-app",
    "prompt": "implement pull-to-refresh on the notifications screen with optimistic UI updates",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 11,
    "duration_s": 190,
    "slug": "bright-coding-wolf",
    "branch": "feat/notifications-refresh",
    "session_file": null
  },
  {
    "ts": "2026-03-23T11:00:00Z",
    "session": "q7r8s9t0",
    "project": "mobile-app",
    "cwd": "/home/dev/repos/mobile-app",
    "prompt": "fix the keyboard dismiss behavior on the chat input. it should not scroll to top when dismissing",
    "response": "Fixed the issue by updating the error handling logic.",
    "effort_total": 12,
    "duration_s": 222,
    "slug": "bright-coding-wolf",
    "branch": "feat/notifications-refresh",
    "session_file": null
  },
  {
    "ts": "2026-03-23T10:42:00Z",
    "session": "q7r8s9t0",
    "project": "mobile-app",
    "cwd": "/home/dev/repos/mobile-app",
    "prompt": "add haptic feedback to the pull-to-refresh gesture and the send button",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 10,
    "duration_s": 170,
    "slug": "bright-coding-wolf",
    "branch": "feat/notifications-refresh",
    "session_file": null
  },
  {
    "ts": "2026-03-23T10:20:00Z",
    "session": "i9j0k1l2",
    "project": "infra",
    "cwd": "/home/dev/repos/infra",
    "prompt": "setup the new CI pipeline for canary deployments using github actions",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 9,
    "duration_s": 168,
    "slug": "swift-deploying-eagle",
    "branch": "infra/redis-migration",
    "session_file": null
  },
  {
    "ts": "2026-03-23T09:55:00Z",
    "session": "m3n4o5p6",
    "project": "docs",
    "cwd": "/home/dev/repos/docs",
    "prompt": "create a troubleshooting section for common webhook delivery failures",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 9,
    "duration_s": 168,
    "slug": "gentle-writing-owl",
    "branch": "docs/api-v2-guide",
    "session_file": null
  },
  {
    "ts": "2026-03-23T09:30:00Z",
    "session": "a1b2c3d4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "build the admin dashboard page for managing API keys with revocation support",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 10,
    "duration_s": 182,
    "slug": "eager-dancing-fox",
    "branch": "fix/auth-redirect",
    "session_file": null
  },
  {
    "ts": "2026-03-22T22:15:00Z",
    "session": "u1v2w3x4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "fix the race condition in the websocket reconnection logic that causes duplicate messages",
    "response": "Fixed the issue by updating the error handling logic.",
    "effort_total": 11,
    "duration_s": 208,
    "slug": "quiet-fixing-cat",
    "branch": "fix/websocket-reconnect",
    "session_file": null
  },
  {
    "ts": "2026-03-22T22:00:00Z",
    "session": "u1v2w3x4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "add connection health monitoring with automatic reconnect and exponential backoff",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 11,
    "duration_s": 192,
    "slug": "quiet-fixing-cat",
    "branch": "fix/websocket-reconnect",
    "session_file": null
  },
  {
    "ts": "2026-03-22T21:40:00Z",
    "session": "u1v2w3x4",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "refactor the event bus to use a proper pub/sub pattern instead of direct coupling",
    "response": "Refactored the code to use the new pattern while maintaining backward compatibility.",
    "effort_total": 11,
    "duration_s": 192,
    "slug": "quiet-fixing-cat",
    "branch": "fix/websocket-reconnect",
    "session_file": null
  },
  {
    "ts": "2026-03-22T21:20:00Z",
    "session": "y5z6a7b8",
    "project": "cli-tool",
    "cwd": "/home/dev/repos/cli-tool",
    "prompt": "implement the interactive config wizard with inquirer prompts and validation",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 10,
    "duration_s": 182,
    "slug": "bold-building-hawk",
    "branch": "feat/config-wizard",
    "session_file": null
  },
  {
    "ts": "2026-03-22T21:00:00Z",
    "session": "y5z6a7b8",
    "project": "cli-tool",
    "cwd": "/home/dev/repos/cli-tool",
    "prompt": "add shell completion generation for bash, zsh, and fish",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 8,
    "duration_s": 140,
    "slug": "bold-building-hawk",
    "branch": "feat/config-wizard",
    "session_file": null
  },
  {
    "ts": "2026-03-22T20:35:00Z",
    "session": "y5z6a7b8",
    "project": "cli-tool",
    "cwd": "/home/dev/repos/cli-tool",
    "prompt": "create a progress bar component for long-running operations like file uploads",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 10,
    "duration_s": 184,
    "slug": "bold-building-hawk",
    "branch": "feat/config-wizard",
    "session_file": null
  },
  {
    "ts": "2026-03-22T20:10:00Z",
    "session": "c9d0e1f2",
    "project": "infra",
    "cwd": "/home/dev/repos/infra",
    "prompt": "migrate the postgres database from 14 to 16 with zero downtime using logical replication",
    "response": "Refactored the code to use the new pattern while maintaining backward compatibility.",
    "effort_total": 11,
    "duration_s": 206,
    "slug": "steady-migrating-deer",
    "branch": "infra/pg16-migration",
    "session_file": null
  },
  {
    "ts": "2026-03-22T19:50:00Z",
    "session": "c9d0e1f2",
    "project": "infra",
    "cwd": "/home/dev/repos/infra",
    "prompt": "check the replication lag between primary and replica before cutover",
    "response": "Reviewed the implementation and identified key areas for improvement.",
    "effort_total": 9,
    "duration_s": 166,
    "slug": "steady-migrating-deer",
    "branch": "infra/pg16-migration",
    "session_file": null
  },
  {
    "ts": "2026-03-22T19:30:00Z",
    "session": "c9d0e1f2",
    "project": "infra",
    "cwd": "/home/dev/repos/infra",
    "prompt": "run the post-migration validation script and verify all foreign key constraints are intact",
    "response": "Tests passed successfully. All assertions verified.",
    "effort_total": 12,
    "duration_s": 210,
    "slug": "steady-migrating-deer",
    "branch": "infra/pg16-migration",
    "session_file": null
  },
  {
    "ts": "2026-03-22T16:00:00Z",
    "session": "g3h4i5j6",
    "project": "mobile-app",
    "cwd": "/home/dev/repos/mobile-app",
    "prompt": "analyze the crash reports from the last release and prioritize the top 5 issues",
    "response": "Reviewed the implementation and identified key areas for improvement.",
    "effort_total": 10,
    "duration_s": 188,
    "slug": "sharp-debugging-lynx",
    "branch": "fix/mobile-crashes",
    "session_file": null
  },
  {
    "ts": "2026-03-22T15:30:00Z",
    "session": "g3h4i5j6",
    "project": "mobile-app",
    "cwd": "/home/dev/repos/mobile-app",
    "prompt": "fix the memory leak in the image cache that causes OOM on older devices",
    "response": "Fixed the issue by updating the error handling logic.",
    "effort_total": 10,
    "duration_s": 172,
    "slug": "sharp-debugging-lynx",
    "branch": "fix/mobile-crashes",
    "session_file": null
  },
  {
    "ts": "2026-03-22T15:00:00Z",
    "session": "g3h4i5j6",
    "project": "mobile-app",
    "cwd": "/home/dev/repos/mobile-app",
    "prompt": "update the navigation stack to react-navigation v7 and fix the breaking changes",
    "response": "Refactored the code to use the new pattern while maintaining backward compatibility.",
    "effort_total": 10,
    "duration_s": 188,
    "slug": "sharp-debugging-lynx",
    "branch": "fix/mobile-crashes",
    "session_file": null
  },
  {
    "ts": "2026-03-21T17:00:00Z",
    "session": "k7l8m9n0",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "implement the new onboarding flow with step-by-step wizard and progress tracking",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 11,
    "duration_s": 190,
    "slug": "warm-onboarding-otter",
    "branch": "feat/onboarding-wizard",
    "session_file": null
  },
  {
    "ts": "2026-03-21T16:30:00Z",
    "session": "k7l8m9n0",
    "project": "web-app",
    "cwd": "/home/dev/repos/web-app",
    "prompt": "add analytics events for each onboarding step to track funnel drop-off",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 10,
    "duration_s": 170,
    "slug": "warm-onboarding-otter",
    "branch": "feat/onboarding-wizard",
    "session_file": null
  },
  {
    "ts": "2026-03-21T16:00:00Z",
    "session": "o1p2q3r4",
    "project": "data-pipeline",
    "cwd": "/home/dev/repos/data-pipeline",
    "prompt": "build the ETL job for syncing user events from kafka to the analytics warehouse",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 10,
    "duration_s": 188,
    "slug": "fast-piping-salmon",
    "branch": "feat/etl-kafka",
    "session_file": null
  },
  {
    "ts": "2026-03-21T15:30:00Z",
    "session": "o1p2q3r4",
    "project": "data-pipeline",
    "cwd": "/home/dev/repos/data-pipeline",
    "prompt": "add dead letter queue handling for malformed events that fail schema validation",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 10,
    "duration_s": 188,
    "slug": "fast-piping-salmon",
    "branch": "feat/etl-kafka",
    "session_file": null
  },
  {
    "ts": "2026-03-21T15:00:00Z",
    "session": "o1p2q3r4",
    "project": "data-pipeline",
    "cwd": "/home/dev/repos/data-pipeline",
    "prompt": "install and configure the avro schema registry for event versioning",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 9,
    "duration_s": 164,
    "slug": "fast-piping-salmon",
    "branch": "feat/etl-kafka",
    "session_file": null
  },
  {
    "ts": "2026-03-21T14:00:00Z",
    "session": "s5t6u7v8",
    "project": "docs",
    "cwd": "/home/dev/repos/docs",
    "prompt": "review the changelog for the upcoming release and make sure all breaking changes are documented",
    "response": "Reviewed the implementation and identified key areas for improvement.",
    "effort_total": 12,
    "duration_s": 220,
    "slug": "wise-reviewing-raven",
    "branch": "docs/release-changelog",
    "session_file": null
  },
  {
    "ts": "2026-03-21T13:30:00Z",
    "session": "s5t6u7v8",
    "project": "docs",
    "cwd": "/home/dev/repos/docs",
    "prompt": "write the getting started guide for new contributors including local dev setup",
    "response": "Documentation updated with comprehensive examples and migration notes.",
    "effort_total": 10,
    "duration_s": 186,
    "slug": "wise-reviewing-raven",
    "branch": "docs/release-changelog",
    "session_file": null
  },
  {
    "ts": "2026-03-20T11:00:00Z",
    "session": "w9x0y1z2",
    "project": "cli-tool",
    "cwd": "/home/dev/repos/cli-tool",
    "prompt": "refactor the command parser to support nested subcommands and global flags",
    "response": "Refactored the code to use the new pattern while maintaining backward compatibility.",
    "effort_total": 10,
    "duration_s": 178,
    "slug": "nimble-parsing-hare",
    "branch": "refactor/command-parser",
    "session_file": null
  },
  {
    "ts": "2026-03-20T10:30:00Z",
    "session": "w9x0y1z2",
    "project": "cli-tool",
    "cwd": "/home/dev/repos/cli-tool",
    "prompt": "add JSON and YAML output formatters with configurable pretty-printing",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 9,
    "duration_s": 168,
    "slug": "nimble-parsing-hare",
    "branch": "refactor/command-parser",
    "session_file": null
  },
  {
    "ts": "2026-03-20T10:00:00Z",
    "session": "a2b3c4d5",
    "project": "infra",
    "cwd": "/home/dev/repos/infra",
    "prompt": "setup automated database backups to S3 with point-in-time recovery support",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 10,
    "duration_s": 178,
    "slug": "solid-backing-tortoise",
    "branch": "infra/db-backups",
    "session_file": null
  },
  {
    "ts": "2026-03-20T09:30:00Z",
    "session": "a2b3c4d5",
    "project": "infra",
    "cwd": "/home/dev/repos/infra",
    "prompt": "create IAM roles and policies for the backup service with least-privilege access",
    "response": "Added the new feature with proper validation and error handling.",
    "effort_total": 11,
    "duration_s": 190,
    "slug": "solid-backing-tortoise",
    "branch": "infra/db-backups",
    "session_file": null
  }
]
;
